### ISSUE TITLE
Can't compile with Swift3

### ISSUE THREAD

**Issue by PranKe01** [Alliants/ALAccordion#13]
Hey there!
I updated my project to Swift3, but now it does not compile, when using ALAccordion v0.4.0.

I get an error "Command failed due to signal: Segmentation fault: 11"
While emitting SIL for getter for headerView at [filelocation]

```
lazy var headerView: UIView = {
    ...
}()
```

When I remove the "lazy" keyword, it compiles, but then the UITapGestureRecognizer doesn't work anymore.

Any ideas, what's wrong?

Thanks!

**Comment by sam899** [comment]
Hey @PranKe01 

I've just pushed an update to the develop branch - can you try it out to see if it solves your problem? 

`pod 'ALAccordion', git: 'https://github.com/Alliants/ALAccordion.git', branch: 'develop'`

If not, what version of Xcode and Cocoapods are you using? Does the example project work?
I've tested the develop branch with Xcode 8.1 and Cocoapods 1.1.1

**Comment by PranKe01** [comment]
It doesn't work with the develop branch. But when I looked at the example project I realised, that it is not implemented like in the docs! I can't find a single lazy-command here: https://github.com/Alliants/ALAccordion/blob/master/Example/ALAccordion%20Example/Controllers/ALFirstSectionViewController.swift
I will try to implement it like in the example...

**Comment by PranKe01** [comment]
Okay, after implementing it the way like in the example, it does work :) The Docs REALLY should be updates ;)

**Comment by sam899** [comment]
Good catch - Sorry about that!

I'll update it now :-)

**Comment by PranKe01** [comment]
I debugged the code now and I realised, that the override init() function is never called, but the required init?() is. Is it save to remove the override of the init function?

**Comment by sam899** [comment]
The different initializers are executed depending on how you instantiate the class. While only one at a time will be executed, I find implementing all inits is generally a good idea to future-proof the class where you may use it differently.

That said, when I updated the README, I also cleaned up the example and removed the initializers completely so check that out to see if you prefer the alternative.

**Comment by PranKe01** [comment]
Yeah, that's even better and does work :) Thank you!
