### ISSUE TITLE
Choose size of sections?

### ISSUE THREAD

**Issue by picklejuice22** [Alliants/ALAccordion#5]
I'm a complete n00b when it comes to constraints. How is it possible to choose the size of the sections when they're closed?

**Comment by sam899** [comment]
In the example project, the constraints are all set by code, but the below concept applies if you use interface builder.

For the example project, the header sections size is determined by the views intrinsic content size (i.e how much space the content inside the headers need to display optimally).
If we take `ALSingleLineHeaderView` as an example, we have the vertical constraint:

```swift
let vertical = NSLayoutConstraint.constraintsWithVisualFormat("V:|[topSeparator(1)]-(15)-[titleLabel]-(15)-[bottomSeparator(1)]|", options: [], metrics: nil, views: views)
```

The topSeparator and bottomSeparator have a height of 1, and the titleLabel has an intrinsic content size of the space required by the text inside it.

If you need to specify a fixed height for the header, ignoring the intrinsic content size, you can simply add another constraint to the view, for example:

```swift
let heightConstraint = NSLayoutConstraint(item: self, attribute: .Height, relatedBy: .Equal, toItem: nil, attribute: .NotAnAttribute, multiplier: 1.0, constant: 250.0)
```

This is quite a simple example, but if you had a more complicated header view (eg 2 labels), I'd recommend reading up on the content hugging / compression priority properties. This will give you the most control over how your subviews would resize.

Finally, it's worth checking the `ALExpandingHeaderView` class in the example - it shows how you have a different height for the header when open and closed.

**Comment by enstulen** [comment]
Thanks a lot!

**Comment by picklejuice22** [comment]
Thanks a lot! :+1:
