### ISSUE TITLE
Trouble while installing

### ISSUE THREAD

**Issue by Stan92** [Alliants/ALAccordion#6]
Hi,
I try to follow how to use your example, I got these errors..during the pod install

[!] The `ALAccordion Example [Debug]` target overrides the `EMBEDDED_CONTENT_CONTAINS_SWIFT` build setting defined in `Pods/Target Support Files/Pods/Pods.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

And when I try to run the projet I got this error :
Quick.h (include of non-modular header inside framework module 'Quick.Quick'
Could not build Objective-C module 'Quick'

**Comment by sam899** [comment]
Thanks for the report. I've updated the example to work with the latest version of cocoapods. Please try again!
