### ISSUE TITLE
Dynamically add sections

### ISSUE THREAD

**Issue by chris-247-sloan** [Alliants/ALAccordion#8]
I'm building an app where I'd like the subsequent accordion sections ( ie section 2 and down) to change depending on a choice in the first accordion section. I have the selection reporting back to the AccordionController subclass correctly. 

I can see from the source that when setViewControllers is called it appends incoming viewControllers to the instance variable 'sections', which is what I am attempting to do. 

When I do this the animation jumps to close the first section. Once the dynamic sections have been added and displayed closed once, the animations work as expected. 

Have you any advice as to how I could add the dynamic sections and keep the animation smooth? 

Thanks in advance.

**Comment by sam899** [comment]
Hi Chris,

ALAccordion wasn't originally designed to support dynamic sections. However, I've created a new branch feature/dynamic_sections which supports this.

Give it a go and let me know if it's what you're after. Then I'll push the update through to cocoapods.

The following methods have been added to the ALAccordionController:
```swift
public func setViewControllers(viewControllers: [UIViewController], animated: Bool)
public func addViewController(viewController: UIViewController, animated: Bool)
public func insertViewController(viewController: UIViewController, atIndex index: Int, animated: Bool)
public func removeSectionAtIndex(index: Int, animated: Bool)
```

Sam

**Comment by chris-247-sloan** [comment]
Hi Sam, 

Wow. Thank you very much for putting in the extra effort to update ALAccordion. I was only expecting a bit of advice. I'm very grateful. 

I haven't had a chance to look yet as I've been assigned to another task at the minute but hopefully will be returning to my original one next week. I had hoped to be back on it this week. I wanted to respond to let you know that I've not just asked a question and disappeared. 

Thanks again.

**Comment by sam899** [comment]
Hey Chris,

You're welcome!
I've been meaning to add this functionality for a while so you gave me the excuse to do it 🙂

**Comment by chris-247-sloan** [comment]
Hi Sam, 
I have managed to get back on it this morning. 

The new example is great, its 99.9% exactly what I need. 

The one tiny part that is missing is a value for the current number of sections within ALAccordionController. 
My idea is that a selection in the first view controller removes all subsequent controllers before adding back the relevant new ones, and the only way I can see is to have some idea of how many sections are currently set. This way I can push the selection back to the ALAccordionController subclass which can then control the removal and adding of sections / view controllers. 

So I've added 
```
public var countOfSections: Int
{
    //Return the current count of sections
    return self.sections.count
}
```
I can add a pull request if required. 

I'm really pleased with the way my app is progressing now, Thanks very much.

Cheers

**Comment by sam899** [comment]
Hi Chris,

Great news. Would love to see your app when you finish it :-)

I'm not sure I fully understand your use case, but exposing the number of sections sounds like a good idea to me.

Alternatively, I could expose the sections array (readonly). My thoughts on this would be to allow you to not only get the count, but also get access to the view controller in each section. Might help to understand exactly what's inside the accordion.
Would that help your use case at all, or just the count?

**Comment by chris-247-sloan** [comment]
Yes I can see that exposing the sections/ view controllers themselves would also be useful. 

In my case I'm going to have to implement a method of retrieving user input from each sections' view controller to calculate the users progression through the process and this would make it much simpler. 

Cheers.
